# Setting up automated tests for the framework
language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '7.4.9'
  - '8.0'
before_script: composer require phphleb/tests
script: vendor/bin/phpunit vendor/phphleb/tests/